[package]
name = "winkle-kernel"
version = "0.1.0"
authors = ["Mike Dilger <mike@optcomp.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
