#!/bin/sh

# readelf -l target/riscv64imac-unknown-winklekernel-elf/release/kernel
#
# Elf file type is EXEC (Executable file)
# Entry point 0x80000000
# There are 2 program headers, starting at offset 64
#
# Program Headers:
#   Type           Offset             VirtAddr           PhysAddr
#                  FileSiz            MemSiz              Flags  Align
#   LOAD           0x0000000000001000 0x0000000080000000 0x0000000080000000
#                  0x0000000000001420 0x0000000000001420  R E    0x1000
#   LOAD           0x0000000000003000 0x0000000080002000 0x0000000080002000
#                  0x0000000000000008 0x000000007fdfe000  RW     0x1000
#
#  Section to Segment mapping:
#   Segment Sections...
#    00     .text .rodata
#    01     .data .stack .heap
#
# --------------------------------
# We create a binary using dd to extract sections from this elf file:
#
# 	from 0x1000 - 0x1000 + 0x1420
# 	       4096 ..  9248

dd if=target/riscv64imac-unknown-winklekernel-elf/release/kernel \
   of=kernel.bin \
   bs=4096 skip=1 count=2
